name: BleedingMobs
main: me.snowleo.bleedingmobs.BleedingMobs
version: "${project.version}"
authors: [snowleo, Iaccidentally, JustEli]
api-version: "1.15"
commands:
  bleedingmobs:
    description: Change bleedingmobs settings
    usage: /<command> (toggle|reload|toggle-world [worldname]|info|set ...)
    aliases: [bm]
    permission: bleedingmobs.admin

permissions:
  bleedingmobs.admin:
    description: Allow access to admin command
    default: op
  bleedingmobs.bloodstrike:
    description: When enabled in config, only players with this permission will make other creatures and players bleed
    default: true
  bleedingmobs.noblood:
    description: Players with this permission will not bleed
    default: false