name: BleedingMobs
main: me.snowleo.bleedingmobs.BleedingMobs
version: 3.4c
authors: [snowleo]
commands:
  bleedingmobs:
    description: Change bleedingmobs settings
    usage: /<command> (toggle|reload|toggle-world [worldname]|info|set ...)
    aliases: [bm]
    permission: bleedingmobs.admin
    
permission:
  bleedingmobs.admin:
    description: Allow access to admin command
    default: op