name: BleedingMobs
main: me.snowleo.bleedingmobs.BleedingMobs
version: 3.6b
authors: [snowleo]
commands:
  bleedingmobs:
    description: Change bleedingmobs settings
    usage: /<command> (toggle|reload|toggle-world [worldname]|info|set ...)
    aliases: [bm]
    permission: bleedingmobs.admin
    
permissions:
  bleedingmobs.admin:
    description: Allow access to admin command
    default: op
  bleedingmobs.bloodstrike:
    description: When enabled in config, only players with this permission will make other creatures and players bleed
    default: true