name: BleedingMobs
main: me.snowleo.bleedingmobs.BleedingMobs
version: 4.4
authors: [snowleo, Iaccidentally]
commands:
  bleedingmobs:
    description: Change bleedingmobs settings
    usage: /<command> (toggle|reload|toggle-world [worldname]|info|set ...)
    aliases: [bm]
    permission: bleedingmobs.admin
    
permissions:
  bleedingmobs.admin:
    description: Allow access to admin command
    default: op
  bleedingmobs.update:
    description: Show update notices to player
    default: op
  bleedingmobs.bloodstrike:
    description: When enabled in config, only players with this permission will make other creatures and players bleed
    default: true
  bleedingmobs.noblood:
    description: Players with this permission will not bleed
    default: false